### ISSUE TITLE
com.amazonaws.AbortedException

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-s3#42]
After the changes in #41 `AwsOcket#write()` doesn't work:

```
com.amazonaws.AbortedException:
	at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:51)
	at com.amazonaws.internal.SdkFilterInputStream.markSupported(SdkFilterInputStream.java:107)
	at com.amazonaws.http.AmazonHttpClient.beforeRequest(AmazonHttpClient.java:450)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:355)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3649)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1414)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.4`
